apiVersion: v2
name: eth-validator
description: A Helm chart for deploying Ethereum Sepolia testnet validators with Geth and Lighthouse
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ethereum
  - validator
  - geth
  - lighthouse
  - sepolia
  - testnet
maintainers:
  - name: eth-testnet-validator
sources:
  - https://github.com/ethereum/go-ethereum
  - https://github.com/sigp/lighthouse
